### ISSUE TITLE
Problem adjusting the order of text, tables and figures

### ISSUE THREAD

**Issue by ronnyhdez** [ronnyhdez/eas_585_lab_01#3]
When introducing tables to the document, the final pdf output does not shows relation with the order given in the Rmd document.

**Comment by ronnyhdez** [comment]
Solution is stated in the [RStudio community forum](https://community.rstudio.com/t/cant-control-position-of-tables-and-figures-in-knitted-pdf-document/37364/3).

We need to create a file called `my_header.tex` that contains the following:

```
\usepackage{float}
\let\origfigure\figure
\let\endorigfigure\endfigure
\renewenvironment{figure}[1][2] {
    \expandafter\origfigure\expandafter[H]
} {
    \endorigfigure
}
```

Next, on the yaml we need to introduce the following:

```
output:
  pdf_document:
    fig_caption: yes        
    includes:  
      in_header: my_header.tex
```

And problem solved!
